version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
