name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test / Lint / Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Run tests
        run: |
          if [ -f yarn.lock ]; then
            yarn test --silent
          else
            npm test --silent
          fi

      - name: Run linter
        run: |
          if [ -f yarn.lock ]; then
            yarn lint
          else
            npm run lint
          fi

      - name: Build app (if present)
        run: |
          node -e "process.exit(require('./package.json').scripts && require('./package.json').scripts.build ? 0 : 1)" \
            && ( if [ -f yarn.lock ]; then yarn build; else npm run build; fi ) \
            || echo "No build script found - skipping build"
